parameters:
#    maindata.example.class: main\dataBundle\Example

services:
#    maindata.example:
#        class: %maindata.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
